import { autoGeneratedNewsApi } from './autoGeneratedNewsApi';
import type {
  PaginatedArticleListRead,
  ArticleRead,
} from '../types/newsApiType';

export const extendedNewsPreviewApi = autoGeneratedNewsApi.injectEndpoints({
  endpoints: builder => ({
    getNewsPreview: builder.query<ArticleRead, void>({
      query: () => ({
        url: '/v4/articles/',
        params: { limit: 1 },
      }),
      // NOTE: Трансформирую и валидирую ответ сервера до попадения в redux
      transformResponse: (response: PaginatedArticleListRead): ArticleRead => {
        const newsPreview = response?.results?.[0];
        if (!newsPreview) {
          throw new Error(
            'Сервер вернул пустой ответ: новость превью не найдена',
          );
        }

        return newsPreview;
      },
    }),
  }),
  overrideExisting: false,
});

export const { useGetNewsPreviewQuery } = extendedNewsPreviewApi;
